version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_panel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nestuser
      DB_PASS: nestpass
      DB_NAME: nestdb
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  seed:
    image: node:20-alpine
    container_name: vehicle_seed
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: node seed-vehicles.js
    depends_on:
      - nestjs
    restart: "no"

volumes:
  postgres_data:
